/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#dce9ff',
        'outline-variant': '#c5c6cf',
        background: '#f8f9ff',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-container': '#fefcff',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'on-primary-container': '#8293ba',
        'primary-container': '#1a2b4c',
        'on-surface': '#0b1c30',
        'tertiary-container': '#003320',
        secondary: '#0051d5',
        'surface-bright': '#f8f9ff',
        'on-secondary-fixed': '#00174b',
        tertiary: '#001c10',
        surface: '#f8f9ff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#00a774',
        'on-primary-fixed-variant': '#364669',
        'on-primary-fixed': '#071b3b',
        'surface-container': '#e5eeff',
        primary: '#031636',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#316bf3',
        'on-surface-variant': '#44474e',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#003ea8',
        'surface-container-low': '#eff4ff',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#b6c6f0',
        outline: '#75777f',
        'inverse-surface': '#213145',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#0b1c30',
        'on-secondary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'secondary-fixed': '#dbe1ff',
        'surface-tint': '#4e5e82',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b6c6f0',
        'primary-fixed': '#d8e2ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-width': '280px',
        'sidebar-collapsed': '80px',
        base: '8px',
        'gutter-md': '16px',
        'container-padding': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
